<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Example10\Example10.csproj" />
    <ProjectReference Include="..\Example11\Example11.csproj" />
    <ProjectReference Include="..\Example13\Example13.csproj" />
    <ProjectReference Include="..\Example3\Example3.csproj" />
    <ProjectReference Include="..\Example4\Example4.csproj" />
    <ProjectReference Include="..\Example5\Example5.csproj" />
    <ProjectReference Include="..\Example6\Example6.csproj" />
    <ProjectReference Include="..\Example7\Example7.csproj" />
    <ProjectReference Include="..\Example8\Example8.csproj" />
    <ProjectReference Include="..\Example9\Example9.csproj" />
    <ProjectReference Include="..\ExampleQuanly\ExampleQuanly.csproj" />
    <ProjectReference Include="..\ExampleSQL\ExampleSQL.csproj" />
    <ProjectReference Include="..\Example\Example1.csproj" />
    <ProjectReference Include="..\Form2\Example2.csproj" />
    <ProjectReference Include="..\Game\Game.csproj" />
  </ItemGroup>

</Project>